- id: trailing-whitespace
  name: Trim Trailing Whitespace
  description: This hook trims trailing whitespace.
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: check-json
